objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi:
    cm:
      description: HttpApi Plugin for BIG-IP Next Central Manager devices
      name: cm
      version_added: 1.0.0
  inventory: {}
  lookup: {}
  module:
    cm_device_info:
      description: Collect information from CM devices
      name: cm_device_info
      namespace: ''
      version_added: 1.0.0
    cm_files:
      description: Manage files uploads/deletes on BIG-IP Next CM
      name: cm_files
      namespace: ''
      version_added: 1.0.0
    cm_next_as3_deploy:
      description: Manages Deploying an AS3 declaration to a specified instance managed
        by BIG-IP Next Central Manager.
      name: cm_next_as3_deploy
      namespace: ''
      version_added: 1.0.0
    cm_next_backup_restore:
      description: Backup and restore BIG-IP Next instance configration through CM
      name: cm_next_backup_restore
      namespace: ''
      version_added: 1.0.0
    cm_next_deploy_f5os:
      description: Module to manage deployments of BIG-IP Next instances on F5OS devices
      name: cm_next_deploy_f5os
      namespace: ''
      version_added: 1.0.0
    cm_next_deploy_vmware:
      description: Module to manage deployments of BIG-IP Next instances on VMWARE
      name: cm_next_deploy_vmware
      namespace: ''
      version_added: 1.0.0
    cm_next_discover:
      description: Module to Add/Delete BIG-IP Next Instances onto Central Manager
      name: cm_next_discover
      namespace: ''
      version_added: 1.0.0
    cm_next_files:
      description: Manage BIG-IP Next instance files through CM
      name: cm_next_files
      namespace: ''
      version_added: 1.0.0
    cm_next_global_resiliency_group:
      description: Manages Global Resiliency Group on the Central Manager.
      name: cm_next_global_resiliency_group
      namespace: ''
      version_added: 1.0.0
    cm_next_ha:
      description: Configure High Availability for BIG-IP Next instances.
      name: cm_next_ha
      namespace: ''
      version_added: 1.0.0
    cm_next_ha_failover:
      description: Fail-over BIG-IP Next HA instance on CM
      name: cm_next_ha_failover
      namespace: ''
      version_added: 1.0.0
    cm_next_provider:
      description: Manage providers on Central Manager
      name: cm_next_provider
      namespace: ''
      version_added: 1.0.0
    cm_next_upgrade:
      description: Manage BIG-IP Next instance upgrades through CM
      name: cm_next_upgrade
      namespace: ''
      version_added: 1.0.0
    cm_ssl_certificate_create:
      description: Manages certificate and/or key on the Central Manager.
      name: cm_ssl_certificate_create
      namespace: ''
      version_added: 1.0.0
    cm_ssl_certificate_import:
      description: Manages certificate, key and PKCS12 on the Central Manager.
      name: cm_ssl_certificate_import
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.1.0
